### ISSUE TITLE
I'm struggling to understand elog and clog

### ISSUE THREAD

**Issue by EmmaRocheteau** [MIC-DKFZ/trixi#26]
Can I ask some more about clog and elog? I looked into it as much as I could, and I can see that clog is a 'combined' logger? I don't think I'm understanding the concept of what a logger is supposed to be, and also what the difference between self.elog.print() and self.clog.show_text() is, they seem to result in similar things

**Comment by jenspetersen** [comment]
The combined logger is just for convenience. The combined logger will be constructed from all available loggers (e.g. the experiment logger and a Visdom logger) and inherits all their methods. So when you call `.show_text(...)` on it, it will automatically go through all available loggers and call `.show_text(...)` on them, if it's available. If you only have one logger (the experiment logger), it and the combined logger will be identical!

Let me also give you a quick summary of our loggers. in `trixi.logger` you will find subpackages `file`, `message`, `tensorboard`, `visdom`, which are functional loggers that log to some external recipient (disk, Slack/Telegram, Tensorboard, Visdom). Then there is `plt`, which does sort of the same, because it logs to a matplotlib/seaborn backend, but that's not really external, so these actually return figure objects that you can use for something else (e.g saving to disk -> the PlotFileLoggers use them). Finally there's the `logger.experiment` subpackage, which contains loggers that create the consistent folder structure and automatically direct stuff to where it's supposed to be (plots to the "plot" folder etc.). These are basically the logging backend of the (Pytorch)Experiment, which is why they are automatically created.

Now the `.print` vs. `.show_text` difference: The default name for a logging method in our framework is `.show_X`, so every logger that can handle text should have a `.show_text` method. The `.print` method is more of a convenience function that we haven't been super consistent with (e.g. the VisdomLoggers don't have it even though they can display text). When it's there, it does the same as `.show_text`, but can accept multiple arguments that will just be concatenated before logging (like the Python builtin `.print`!). If you just log a single string, using `.show_text` is cleaner :)

I hope that wasn't too confusing, it's great to get a beginner's perspective to see which parts need to become more accessible!
