### ISSUE TITLE
Corrupted Installation

### ISSUE THREAD

**Issue by justusschock** [MIC-DKFZ/trixi#4]
Hi,

the Installation via PyPi fails, because the `requirements_full.txt` cannot be found.

Just to let you know.

EDIT:
Installation from git was successful, but importing failed due to missing subpackages (git installation fixed in #5 )

**Comment by jenspetersen** [comment]
It should work now. Turns out there is a find_packages function in setuptools, which does essentially the same as your pull request. I don't really understand why, but for me this also fixed the requirements_full.txt error. As you see, we're in the process of building expertise here :D Closing for now, please let us know if the error persists!
