### ISSUE TITLE
Install Requirements 

### ISSUE THREAD

**Issue by justusschock** [MIC-DKFZ/trixi#7]
Hi, 

Since `trixi` does not necessarily depend on PyTorch, would it be possible to leave it out of the dependencies inside the `setup.py` and on pip?

I'd like to use `trixi` in a project but don't want a hard PyTorch dependency. From what I've seen, an optional dependency should be sufficient.

Greetings, 
Justus

**Comment by GregorKoehler** [comment]
@dzimmerer, @jenspetersen: maybe we could use `requirements_base.txt` in the setup to support this use case?
https://github.com/MIC-DKFZ/trixi/blob/develop/setup.py#L33

**Comment by jenspetersen** [comment]
That's what the different requirements files are meant for, but so far we haven't implemented anything that allows you to select different sets of dependencies. The easiest way to go would be to pass the hard requirements to install_requires and the optional dependencies to extras_require. I've implemented this on the gh-issue-7-optional-dependencies branch. The problem is that we want the default behaviour to be a complete install with PyTorch, at least when installing from PyPI, so if you @justusschock have any experience with this, please let us know :) Also, could you describe your use case in more detail? Will you be using trixi from PyPI in your project? If so, maybe we could provide an additional trixi-slim package with just the essentials?

**Comment by justusschock** [comment]
I'd like to use the PyPI version and especially the logging structure. I thought that trixi should be fine installing without pytorch, but I can understand, if you want a full install with PyTorch. 

The additional trixi-slim package would be perfect for my case (at least if there is a mechanism, that would replace it by the full trixi if one wants to install it afterwards). Another way to go, would probably be to provide a slim package and make the full package depend on this one?

**Comment by jenspetersen** [comment]
There is now a trixi-slim package. Note that it is accessed via "trixi" in python and I have no idea what happens if you try to install it along with the regular trixi package (feel free to try and report :)).

**Comment by justusschock** [comment]
Just to let you know: I tried it (installed first trixi and then trixi slim) and it does not complain at installation time. The paths at importing it point to the full-featured version, so in this case the slim variant seems to be just ignored.
